name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main", "develop" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: cargo test --release --verbose
    - name: Run tests feature game
      run: cargo test --release --features game --verbose
    - name: Run tests feature analysis
      run: cargo test --release --features analysis --verbose
    - name: Run tests all features
      run: cargo test --release --all-features --verbose

  doc:
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'push'
    
    steps:
    - uses: actions/checkout@v2
    - name: Run doc
      run: cargo doc --no-deps --all-features

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./target/doc/
