name: Rust

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: cargo test --release --verbose

  doc:
    runs-on: ubuntu-latest
    needs: test
    if: (github.event_name == 'push' && github.event.push.ref == 'main') || (github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main')
    
    steps:
    - uses: actions/checkout@v2
    - name: Run doc
      run: cargo doc --no-deps

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./target/doc/
